name: 编译到Action的Artifacts

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  compile2ActionArtifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          
      - name: Make All
        run: |
          ./package.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: release/
