name: README-to-DockerHub

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sync README.md to DockerHub frps
        uses: actionhippie/pushrm@v1
        with:
          provider: dockerhub
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          target: ${{ secrets.DOCKERHUB_USERNAME }}/frps


      - name: Sync README.md to DockerHub frpc
        uses: actionhippie/pushrm@v1
        with:
          provider: dockerhub
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          target: ${{ secrets.DOCKERHUB_USERNAME }}/frpc
  